### ISSUE TITLE
[EXT REQ] give_admin

### ISSUE THREAD

**Issue by JosefCantz** [Alberto-X3/Alberto-X3-V3#30]
### Extension Name

Admin-Giver

### What are the benefits of having such an extension? Please describe.

Ein gewisser Ingo2004 hat Admin verdient und sollte ihn auch bekommen, aber ein Albert tut dies nicht. Dafür müssen wir eine Lösung finden.

### Describe the solution you'd like

Der Bot gibt Ingo2004 die Administraty-Rolle

### Checklist

- [X] I have searched the open extension requests for ``duplicates``.
- [X] I have searched the closed extension requests for ``wontadd``'s.

### Additional Information

Flugtickets ans andere Ende der Welt sind bestellt um vor den wütenden Albert zu fliehen

**Comment by AlbertUnruh** [comment]
Aus Sicherheitsgründen wird diese Extension nicht implementiert.
~~
Due to security concerns this extension won't be implemented.
